export const UZYTKOWNICY_URL = 'http://localhost:3000/uzytkownicy'
// You have to set this the same as the count of users in userState... f.e.comment data in export const users, leaving empty array.
// That's because there is neither real db nor a dedicated test db.
export const INITIAL_USERS_IN_DATABASE_COUNT = 0
export const ADD_USER_BTN_DT = 'addUserBtn'
export const EDIT_USER_BTN_DT = 'editUserBtn'
export const DELETE_USER_BTN_DT = 'deleteUserBtn'
export const FIRST_NAME_INPUT_DT = 'firstNameInput'
export const LAST_NAME_INPUT_DT = 'lastNameInput'
export const EMAIL_INPUT_DT = 'emailInput'
export const PHONE_INPUT_DT = 'phoneInput'
export const SUBMIT_FORM_BTN_DT = 'submitBtn'
export const CANCEL_FORM_BTN_DT = 'cancelBtn'
export const FULL_NAME_INPUT_DT = 'fullNameInput'
export const CLOSE_WINDOW_DT = 'closeWindowBtn'
export const TEST_FIRST_NAME = 'New'
export const TEST_LAST_NAME = 'Test'
export const TEST_EMAIL = 'test@example.com'
export const WRONG_TEST_EMAIL = 'testaexample.com'
export const TEST_PHONE = '123456789'
export const EDITED_FIRST_NAME = 'Edited'
export const EDITED_LAST_NAME = 'Editedtest'
export const EDITED_TEST_EMAIL = 'edited@example.com'
export const EDITED_PHONE = '9876543211'
export const USER_EDIT_MODAL_TITLE = 'Edycja użytkownika'
export const USER_ADD_MODAL_TITLE = 'Dodawanie użytkownika'
export const USER_DELETE_MODAL_TITLE = 'Usuwanie użytkownika'
export const ERROR_MODAL_TITLE = 'Error'
